logging:
  level: INFO
  loggers:
    com.dropwizard: DEBUG
database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/todo?autoReconnect=true&useSSL=false
  user: MSYQL_USERNAME_HERE
  # Look for storing encrypted password
  password: MSYQL_PASSWORD_HERE
  maxWaitForConnection: 1s
  validationQuery: "/* ToDoService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true
